open_graph:
  enable: true
  twitter_id: # for open_graph meta

logo:
  subtitle: 'welcome! | HOPE YOU A JOYFUL DAY~' # '文字1 | 文字2' (鼠标放上去会切换到文字2)

footer:
  trying:
    icon: /images/kazama.ico
    url: https://www.baidu.com # 咋没见到用处呢呜呜